wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711296132.669385
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
l2_regularization:
  desc: null
  value: 0.8429411559403799
learning_rate:
  desc: null
  value: 0.23849451744750316
max_bins:
  desc: null
  value: 138
max_depth:
  desc: null
  value: 12
max_iter:
  desc: null
  value: 845
max_leaf_nodes:
  desc: null
  value: 75
min_samples_leaf:
  desc: null
  value: 57
