wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.5216004637612123
min_impurity_decrease:
  value: 0.06954020086639447
min_samples_leaf:
  value: 3
min_samples_split:
  value: 2
n_estimators:
  value: 19
