wandb_version: 1

max_depth:
  value: 6
max_features:
  value: 0.8681556645773868
min_impurity_decrease:
  value: 0.08418200890756393
min_samples_leaf:
  value: 2
min_samples_split:
  value: 8
n_estimators:
  value: 12
