wandb_version: 1

max_depth:
  value: 13
max_features:
  value: 0.11841818827540772
min_impurity_decrease:
  value: 0.017166140284359335
min_samples_leaf:
  value: 2
min_samples_split:
  value: 6
n_estimators:
  value: 11
