wandb_version: 1

max_depth:
  value: 11
max_features:
  value: 0.4817583966556626
min_impurity_decrease:
  value: 0.019736805810392933
min_samples_leaf:
  value: 4
min_samples_split:
  value: 10
n_estimators:
  value: 20
