wandb_version: 1

max_depth:
  value: 10
max_features:
  value: 0.4119075333201029
min_impurity_decrease:
  value: 0.019221615934541428
min_samples_leaf:
  value: 2
min_samples_split:
  value: 7
n_estimators:
  value: 20
