wandb_version: 1

max_depth:
  value: 8
max_features:
  value: 0.5922722368634212
min_impurity_decrease:
  value: 0.025299754961986255
min_samples_leaf:
  value: 5
min_samples_split:
  value: 7
n_estimators:
  value: 18
