wandb_version: 1

l2_regularization:
  value: 0.5546614923881591
learning_rate:
  value: 0.26258378692218826
loss:
  value: mean_squared_error
max_bins:
  value: 147
max_depth:
  value: 30
max_iter:
  value: 782
max_leaf_nodes:
  value: 143
min_samples_leaf:
  value: 70
