wandb_version: 1

max_depth:
  value: 7
max_features:
  value: 0.3495536894802362
min_impurity_decrease:
  value: 0.002737379069495294
min_samples_leaf:
  value: 2
min_samples_split:
  value: 2
n_estimators:
  value: 14
