wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.5460568319445116
min_impurity_decrease:
  value: 0.07966836501718164
min_samples_leaf:
  value: 2
min_samples_split:
  value: 8
n_estimators:
  value: 11
