wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.8146179291028761
min_impurity_decrease:
  value: 0.08966937873344483
min_samples_leaf:
  value: 4
min_samples_split:
  value: 9
n_estimators:
  value: 20
