wandb_version: 1

max_depth:
  value: 13
max_features:
  value: 0.6182187714927984
min_impurity_decrease:
  value: 0.06330225011367625
min_samples_leaf:
  value: 4
min_samples_split:
  value: 4
n_estimators:
  value: 19
