wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711284099.682448
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
max_depth:
  desc: null
  value: 12
max_features:
  desc: null
  value: 0.3581973142055579
min_impurity_decrease:
  desc: null
  value: 8.189323735058318e-05
min_samples_leaf:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 6
n_estimators:
  desc: null
  value: 10
