wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.41450972639465633
min_impurity_decrease:
  value: 0.08028655161295467
min_samples_leaf:
  value: 3
min_samples_split:
  value: 6
n_estimators:
  value: 11
