wandb_version: 1

C:
  value: 10
class_weight:
  value: balanced
coef0:
  value: 4.395526802110866
degree:
  value: 3
gamma:
  value: 0.1
kernel:
  value: poly
shrinking:
  value: false
tol:
  value: 0.05527316596248397
