wandb_version: 1

max_depth:
  value: 14
max_features:
  value: 0.23999638250602137
min_impurity_decrease:
  value: 0.009948108754567976
min_samples_leaf:
  value: 3
min_samples_split:
  value: 9
n_estimators:
  value: 19
