wandb_version: 1

max_depth:
  value: 6
max_features:
  value: 0.31681098070520525
min_impurity_decrease:
  value: 0.05777650381259539
min_samples_leaf:
  value: 4
min_samples_split:
  value: 2
n_estimators:
  value: 10
