wandb_version: 1

max_depth:
  value: 6
max_features:
  value: 0.9704629854575696
min_impurity_decrease:
  value: 0.08648589897796116
min_samples_leaf:
  value: 2
min_samples_split:
  value: 7
n_estimators:
  value: 17
