wandb_version: 1

max_depth:
  value: 10
max_features:
  value: 0.2840950847124667
min_impurity_decrease:
  value: 0.047841986064699527
min_samples_leaf:
  value: 4
min_samples_split:
  value: 4
n_estimators:
  value: 18
