wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711296809.615584
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: 22
min_samples_leaf:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 6
n_estimators:
  desc: null
  value: 24
