wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711293408.661646
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
C:
  desc: null
  value: 8.557534919830799
class_weight:
  desc: null
  value: balanced
fit_intercept:
  desc: null
  value: true
intercept_scaling:
  desc: null
  value: 2
max_iter:
  desc: null
  value: 6045
penalty:
  desc: null
  value: l2
tol:
  desc: null
  value: 0.03895296269732932
