wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711110405.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.12.2
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
bootstrap:
  desc: null
  value: true
max_depth:
  desc: null
  value: 7
max_features:
  desc: null
  value: auto
min_samples_leaf:
  desc: null
  value: 4
min_samples_split:
  desc: null
  value: 8
n_estimators:
  desc: null
  value: 19
