wandb_version: 1

max_depth:
  value: 9
max_features:
  value: 0.7456536136130378
min_impurity_decrease:
  value: 0.07334172725717295
min_samples_leaf:
  value: 3
min_samples_split:
  value: 7
n_estimators:
  value: 13
