wandb_version: 1

max_depth:
  value: 13
max_features:
  value: 0.7416865513181159
min_impurity_decrease:
  value: 0.07862804664511691
min_samples_leaf:
  value: 1
min_samples_split:
  value: 3
n_estimators:
  value: 11
