wandb_version: 1

max_depth:
  value: 8
max_features:
  value: 0.6200438671589791
min_impurity_decrease:
  value: 0.0925644186523462
min_samples_leaf:
  value: 3
min_samples_split:
  value: 10
n_estimators:
  value: 17
