wandb_version: 1

method:
  desc: null
  value: random
metric:
  desc: null
  value:
    name: accuracy
    goal: maximize
parameters:
  desc: null
  value:
    n_estimators:
      min: 10
      max: 20
    max_depth:
      min: 5
      max: 15
    sample_rate:
      values:
      - 0.1
      - 0.2
      - 0.3
    test_size:
      values:
      - 0.2
      - 0.3
      - 0.4
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711038738.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.4
      8:
      - 3
      - 5
      13: windows-amd64
