wandb_version: 1

max_depth:
  value: 9
max_features:
  value: 0.515193170544892
min_impurity_decrease:
  value: 0.04720961028524963
min_samples_leaf:
  value: 2
min_samples_split:
  value: 4
n_estimators:
  value: 16
