wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.4817477535457962
min_impurity_decrease:
  value: 0.0816398268426561
min_samples_leaf:
  value: 5
min_samples_split:
  value: 9
n_estimators:
  value: 16
