wandb_version: 1

max_depth:
  value: 7
max_features:
  value: 0.7047346450836128
min_impurity_decrease:
  value: 0.08119823360597013
min_samples_leaf:
  value: 3
min_samples_split:
  value: 4
n_estimators:
  value: 16
