wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.7586243901713674
min_impurity_decrease:
  value: 0.03569076936919093
min_samples_leaf:
  value: 5
min_samples_split:
  value: 6
n_estimators:
  value: 15
