wandb_version: 1

max_depth:
  value: 11
max_features:
  value: 0.2537409656035302
min_impurity_decrease:
  value: 0.03304879104535089
min_samples_leaf:
  value: 4
min_samples_split:
  value: 3
n_estimators:
  value: 13
