wandb_version: 1

max_depth:
  value: 10
max_features:
  value: 0.5825264511315081
min_impurity_decrease:
  value: 0.06654291980942063
min_samples_leaf:
  value: 4
min_samples_split:
  value: 5
n_estimators:
  value: 14
