wandb_version: 1

l2_regularization:
  value: 0.9190768419531798
learning_rate:
  value: 0.04255164710658347
max_bins:
  value: 250
max_depth:
  value: 29
max_iter:
  value: 589
max_leaf_nodes:
  value: 115
min_samples_leaf:
  value: 23
