wandb_version: 1

l2_regularization:
  value: 0.6784644396052703
learning_rate:
  value: 0.11147867034409815
max_bins:
  value: 142
max_depth:
  value: 21
max_iter:
  value: 684
max_leaf_nodes:
  value: 195
min_samples_leaf:
  value: 44
