wandb_version: 1

l2_regularization:
  value: 0.3525181822415313
learning_rate:
  value: 0.14387657491581987
max_bins:
  value: 59
max_depth:
  value: 21
max_iter:
  value: 673
max_leaf_nodes:
  value: 90
min_samples_leaf:
  value: 69
