wandb_version: 1

l2_regularization:
  value: 0.494053210643977
learning_rate:
  value: 0.17702622266472243
max_bins:
  value: 232
max_depth:
  value: 24
max_iter:
  value: 607
max_leaf_nodes:
  value: 216
min_samples_leaf:
  value: 25
