wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711295940.571852
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
l2_regularization:
  desc: null
  value: 0.6784644396052703
learning_rate:
  desc: null
  value: 0.11147867034409815
max_bins:
  desc: null
  value: 142
max_depth:
  desc: null
  value: 21
max_iter:
  desc: null
  value: 684
max_leaf_nodes:
  desc: null
  value: 195
min_samples_leaf:
  desc: null
  value: 44
