wandb_version: 1

max_depth:
  value: 13
max_features:
  value: 0.434829361535788
min_impurity_decrease:
  value: 0.041045650915214366
min_samples_leaf:
  value: 2
min_samples_split:
  value: 9
n_estimators:
  value: 15
