wandb_version: 1

max_depth:
  value: 13
max_features:
  value: 0.9322386816218174
min_impurity_decrease:
  value: 0.09693246794745024
min_samples_leaf:
  value: 4
min_samples_split:
  value: 5
n_estimators:
  value: 16
