wandb_version: 1

max_depth:
  value: 14
max_features:
  value: 0.8623223044829762
min_impurity_decrease:
  value: 0.04544277736984581
min_samples_leaf:
  value: 3
min_samples_split:
  value: 6
n_estimators:
  value: 14
