wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711287359.350448
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.8
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
max_depth:
  desc: null
  value: 5
max_features:
  desc: null
  value: 0.5216004637612123
min_impurity_decrease:
  desc: null
  value: 0.06954020086639447
min_samples_leaf:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 19
