wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.3623744885792805
min_impurity_decrease:
  value: 0.09270888806691371
min_samples_leaf:
  value: 3
min_samples_split:
  value: 2
n_estimators:
  value: 13
