wandb_version: 1

max_depth:
  value: 7
max_features:
  value: 0.8121694784638895
min_impurity_decrease:
  value: 0.047006440335933555
min_samples_leaf:
  value: 4
min_samples_split:
  value: 7
n_estimators:
  value: 14
