wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.928718035872422
min_impurity_decrease:
  value: 0.07011003912280558
min_samples_leaf:
  value: 3
min_samples_split:
  value: 8
n_estimators:
  value: 13
