wandb_version: 1

max_depth:
  value: 12
max_features:
  value: 0.3581973142055579
min_impurity_decrease:
  value: 8.189323735058318e-05
min_samples_leaf:
  value: 1
min_samples_split:
  value: 6
n_estimators:
  value: 10
