wandb_version: 1

max_depth:
  value: 8
max_features:
  value: 0.7042752670066101
min_impurity_decrease:
  value: 0.017729246231845075
min_samples_leaf:
  value: 3
min_samples_split:
  value: 8
n_estimators:
  value: 16
