wandb_version: 1

max_depth:
  value: 8
max_features:
  value: 0.33486629780576593
min_impurity_decrease:
  value: 0.05036603919513926
min_samples_leaf:
  value: 4
min_samples_split:
  value: 5
n_estimators:
  value: 16
