wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.8792762887776011
min_impurity_decrease:
  value: 0.0501250185438297
min_samples_leaf:
  value: 1
min_samples_split:
  value: 6
n_estimators:
  value: 17
