wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.37101678463949406
min_impurity_decrease:
  value: 0.04165375956666513
min_samples_leaf:
  value: 2
min_samples_split:
  value: 8
n_estimators:
  value: 11
