wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.17457937888396768
min_impurity_decrease:
  value: 0.03404684358207466
min_samples_leaf:
  value: 5
min_samples_split:
  value: 9
n_estimators:
  value: 15
