wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.1525049935152467
min_impurity_decrease:
  value: 0.04825450523730564
min_samples_leaf:
  value: 5
min_samples_split:
  value: 5
n_estimators:
  value: 10
