wandb_version: 1

l2_regularization:
  value: 0.9082860168829314
learning_rate:
  value: 0.23008346709500643
loss:
  value: auto
max_bins:
  value: 231
max_depth:
  value: 29
max_iter:
  value: 242
max_leaf_nodes:
  value: 42
min_samples_leaf:
  value: 93
