wandb_version: 1

max_depth:
  value: 5
max_features:
  value: 0.5221964125508235
min_impurity_decrease:
  value: 0.03918241089007743
min_samples_leaf:
  value: 1
min_samples_split:
  value: 3
n_estimators:
  value: 15
