wandb_version: 1

max_depth:
  value: 15
max_features:
  value: 0.8468259502251619
min_impurity_decrease:
  value: 0.07708145168905124
min_samples_leaf:
  value: 3
min_samples_split:
  value: 9
n_estimators:
  value: 12
